### ISSUE TITLE
I want to restore the iphone 5s (a1530) to IOS 9.0, but the tools pop the error say "Device not supported"

### ISSUE THREAD

**Issue by dapengtx** [synackuk/n1ghtshade#104]
Error in libbelladonna.c:300 "Device not supported."Error in libbelladonna.c:643 "Failed to put device in pwned DFU mode."Error in libbelladonna.c:689 "Failed to put device in pwned DFU mode."Failed to boot tethered.

I changed the iphone to DFU mode, but the tools can not connect to the iPhone

please help me finish the restore task, thanks

**Comment by dapengtx** [comment]
the IOS package file is  "iPhone6,1_9.0_13A344_Restore.ipsw"

**Comment by Visualwit** [comment]
Does Not Support A7 Devices, You Can Close This Issue Now. It Is Recommended To Downgrade To 10.3.3 With LeetDown.

**Comment by Grandboy46** [comment]
N1ghtshade does not support 64 bit devices nor it is possible to downgrade to iOS 9 with or without blobs. You can only downgrade to 10.3.3 untethered without blobs and 10.1.x, 10.2.x and 10.3.x with blobs.

**Comment by synackuk** [comment]
Correct, 64 bit devices are currently unsupported
