### ISSUE TITLE
How to build it?

### ISSUE THREAD

**Issue by TXIuTnVsbA** [synackuk/n1ghtshade#11]
i'm try to use 'make',but its error;

null@iMac n1ghtshade % make
Building plib
CC -c atoi.c -o bin/atoi.o
make[2]: arm-elf-gcc-4.7: No such file or directory
make[2]: *** [bin/atoi.o] Error 1
make[1]: *** [plib] Error 2
make: *** [atropine] Error 2

just how to build it ?

**Comment by synackuk** [comment]
@TXIuTnVsbA You need to install arm-elf-gcc from macports. Check the dependencies section of the readme :)

**Comment by TXIuTnVsbA** [comment]
> @TXIuTnVsbA You need to install arm-elf-gcc from macports. Check the dependencies section of the readme :)

thanks my friend
