### ISSUE TITLE
iPad 3,4 becomes green screen when charging

### ISSUE THREAD

**Issue by mba08mc** [synackuk/n1ghtshade#117]

**Comment by Harold62** [comment]
You mean yellow? That would be because it isn't charged enough yet to boot it. Once it's ready it turns white.

**Comment by mba08mc** [comment]
Solved this a really long time ago. Thanks Harold62 but it wasn't that, I messed up somethink while playing with iFunBox. Re-dgraded and it was all fine.
For people seeing this in the future its either what Harold62 said or u were messing around like I did and broke something.
