### ISSUE TITLE
Failed to get packages

### ISSUE THREAD

**Issue by Cellguy16** [synackuk/n1ghtshade#120]
When I open the n1ghtshade app to download a package manager on iOS 6, I receive a message saying that the app could not connect to the internet. I have checked my internet connection, as well as the date and time.
![error](https://user-images.githubusercontent.com/91715223/135567145-c38145ad-f747-46ba-85aa-d59fc3926e02.PNG)
(A screenshot of the error.)

**Comment by darbysauter** [comment]
Me as well

**Comment by darbysauter** [comment]
@Cellguy16 did you ever get this to work? My guess is the server might be down

**Comment by Cellguy16** [comment]
@darbysauter I have not been able to fix the issue. I have checked all day. I suspect that the server had been shut down. From what I can tell, the project seems like it was probably discontinued.

**Comment by darbysauter** [comment]
damn too bad.. I suppose could maybe use another jailbreak once booted although not sure if they would interact well. Worth a shot

**Comment by darbysauter** [comment]
The request from the server looks fine: https://github.com/synackuk/hyoscine/blob/ff5043f4e5690044f72f98d805e1a823797f672f/physostigmine/n1ghtshade_app/N1RootViewController.m#L14

when loading the link manually it downloads the URL. 

The docs for this method say "This method may fail and return nil for various reasons, like bad URLs and file-not-found errors. If you want to handle these errors" url looks fine and as far as I can tell the link is live.

I will quickly build an app to see if I can reproduce it

**Comment by darbysauter** [comment]
well after a while of getting an OS X yosemite VM and old xcode installed i realized its simply something to do with authentication or from a browser as when I curl the URL i get:

`
<html>
<head><title>301 Moved Permanently</title></head>
<body>
<center><h1>301 Moved Permanently</h1></center>
<hr><center>nginx</center>
</body>
</html>
`

@synackuk any idea how to fix this?

**Comment by synackuk** [comment]
Issue is to do with SSL iirc, GitHub updated their SSL requirements to beyond that supported.

**Comment by synackuk** [comment]
I will fix this in the next update by having the packages plist on a separate server

**Comment by darbysauter** [comment]
When do you roughly plan on releasing that?

**Comment by darbysauter** [comment]
@synackuk In the meantime I have built belladonna and hyoscine but I am unable to load my own. I do 

`
$ belladonna/tools/belladonna -w ~/Downloads/iPhone5,3_7.0.1_11A470a_Restore.ipsw
$ belladonna/tools/belladonna -j -d ../hyoscine/hyoscine/hyoscine.img3
$ belladonna/tools/belladonna -b
`

But the n1ghtshade app doesn't show up. If I don't specify the -d flag it installs fine (looks like it downloads from your github). Am I missing something like signing it or why would my custom ramdisk not be working?

**Comment by YvanQu** [comment]
@berketk7 you're a goddamn hero

**Comment by benzbfr** [comment]
> revert date to september 2021 fixes

I've tried this and it doesn't work for me (anymore?). Anybody has an idea or am I doing something wrong?
