### ISSUE TITLE
Cydia Not Showing Up In N1ghtshade App

### ISSUE THREAD

**Issue by Harold62** [synackuk/n1ghtshade#129]
Asks me if i'm connected to the internet (which i am) and shows nothing under "Availible package managers:"

**Comment by lambda-byte** [comment]
install the ssl cert from http://cydia.invoxiplaygames.uk/certificates/

**Comment by Harold62** [comment]
Hi, thanks for the reply but how can i install something from cydia when i can't install cydia due to it not showing up in the N1ghtShade app?

**Comment by CommandoNghia** [comment]
i also have problem with it?

**Comment by CommandoNghia** [comment]
> install the ssl cert from http://cydia.invoxiplaygames.uk/certificates/

Thank you ! , It's my problem.

**Comment by lambda-byte** [comment]
> Hi, thanks for the reply but how can i install something from cydia when i can't install cydia due to it not showing up in the N1ghtShade app?

you dont need cydia to install the cert
