### ISSUE TITLE
iPad gets back to DFU after restoration. 

### ISSUE THREAD

**Issue by PeterGrig1990** [synackuk/n1ghtshade#142]
Am running n1ghshade I macOS Big Sur, V1.0. 
I succeeded I pretty everything. 
Am restoring the iOS 6.0.1 on iPad 3,5.
I see an Apple logo, a progress bar, the bar goes to the end, but after the reboot, it shows another Apple logo (without glossy design) and gets back to DFU screen (iTunes logo + lighting cable)

**Comment by ooglecg** [comment]
that's normal. just boot tethered after this happens

**Comment by elislays08** [comment]
n1ghtshade is a _tethered_ downgrade. You need to boot tethered every time you shut off the device. It's always going to show the Recovery Mode screen until you do this.
