### ISSUE TITLE
iphone 5 ios 6.0/7.1.2

### ISSUE THREAD

**Issue by dausjer** [synackuk/n1ghtshade#15]
try 6.0/7.1.2 iphone 5
5,1 and 5,2
but stuck grooming heap..
how to fix..
osx sierra use

**Comment by synackuk** [comment]
@dausjer How many times have you tested this? Can you try running from terminal with LIBUSB_DEBUG=3 environment variable?

**Comment by dausjer** [comment]
6 hours try...many times try but no luck,just one luck restore 5,2 ios 7.1.2 but not finish just half and get error..so need try again,just copy paste in terminal  LIBUSB_DEBUG=3 this??how about environment variable? how to set this

**Comment by synackuk** [comment]
@dausjer Can you try with the latest beta, when running from the terminal add LIBUSB_DEBUG=3 before the path to the n1ghtshade binary

**Comment by synackuk** [comment]
@dausjer Fixed grooming heap lockup I believe

**Comment by synackuk** [comment]
Closing as fixed
