### ISSUE TITLE
Problem downgrading iPad3,4 to iOS 6.1.3

### ISSUE THREAD

**Issue by SaadAbbassi4** [synackuk/n1ghtshade#16]
Hi,
It's just giving "Failed to restore Device" and on iPad screen it's stuck on:
pwned by synAck ;)
Initialised atropine.

I'm using macOS Sierra and my device was on iOS 10.3.3 the first time i tried it worked but i had an activation error after i tried to delete setup.app but i couldn't restore

**Comment by synackuk** [comment]
@SaadAbbassi4 The second time it didn't work? Did you use a different version of n1gthshade?

**Comment by bodenchristian** [comment]
Is the error caused by deleting the Setup.app? I get this same error on iPhone 5 10.3.3 after deleting it.

<sub>Sent with <a href="http://githawk.com">GitHawk</a></sub>

**Comment by SaadAbbassi4** [comment]
@synackuk No, I used the same version

**Comment by synackuk** [comment]
@SaadAbbassi4 Can you try with beta 12?

**Comment by SaadAbbassi4** [comment]
Thanks! I like the new logo!

**Comment by SaadAbbassi4** [comment]
Hey!
You told me to use beta 12 and it worked! But I had the activation error again so I tried restoring a patched version without setup.app and it gave and error (even if I restore a non-patched version):"Failed to enter pwned recovery mode"
I tried to downgrade to iOS 6.1.3
Thanks!
Edit: I can enter pwned DFU Mode using ipwndfu

**Comment by SaadAbbassi4** [comment]
Sometimes it gives me "Restore failed"

**Comment by synackuk** [comment]
@SaadAbbassi4 

Not entirely clear what the new issues are. Please create a new issue so things can remain organised :)

**Comment by thisIsTheFoxe** [comment]
Had the same prob. with iPhone 5, iOS 6.1.4 on Catalina. What fixed it was getting the (Global) IPSW instead of the (GMS). :)
