### ISSUE TITLE
Black Screen on iPhone 5 after restore

### ISSUE THREAD

**Issue by mrichardist** [synackuk/n1ghtshade#17]
The device gets stuck in dfu mode I believe. The restore is successful, I've tried 6.0 and 6.0.2 but no luck on sierra. If I hope the power button on the iPhone, it turns on for a brief moment then shuts off. I've tried using the boot option on n1ghtshade but it says waiting for dfu mode when I think the device is already on dfu mode, iTunes detects it in DFU mode, the same with 3uTools.

**Comment by synackuk** [comment]
@mrichardist Interesting. Does it restore correctly?

**Comment by mrichardist** [comment]
Yeah it does. It’s after the restore the device is stuck on a black screen

**Comment by StarLord0055** [comment]
When white screen comes and go watch carefully iphone screen back light is on screen works happened with me you check in dark from there try dfu mode

**Comment by mrichardist** [comment]
It is detected as DFU mode after restore

**Comment by synackuk** [comment]
I believe this means the restore was unsuccessful

**Comment by mrichardist** [comment]
Haven't had any successful downgrades, nothing works for me I'm on sierra

**Comment by marleyqp** [comment]
I forgot to click Boot Tethered, maybe the case for you?

**Comment by mrichardist** [comment]
Tried that as well, doesn't do anything. Tried with all betas no luck

**Comment by marleyqp** [comment]
Sorry about that. Hopefully in the next beta 🤞

**Comment by CenoX** [comment]
I was in same situation, device after restore goes into Recovery mode not DFU.
I restored device into iOS 6.1.2, succeed to boot properly with Boot Tethered feature on n1ghtshade beta 12.

@mrichardist check it out.
If you failed to enter pwned DFU or n1ghtshade quit, don't mind it and just keep trying. It works.

**Comment by synackuk** [comment]
This is fixed in [n1ghtshade rc1](https://github.com/synackuk/n1ghtshade/releases/tag/RC1),  you must re-restore your device after upgrading to it.
