### ISSUE TITLE
High Sierra not supported?

### ISSUE THREAD

**Issue by ytrufchev** [synackuk/n1ghtshade#2]
On the read.me it says sierra and up, but on high sierra it's says it requires 10.14. Is there a way to fix this?

**Comment by slingalist** [comment]
It works if you start it from terminal.

**Comment by ytrufchev** [comment]
Thanks :)

**Comment by synackuk** [comment]
@ytrufchev correct, this will be corrected in the next build but currently I want to iron out the restoring bug.

**Comment by synackuk** [comment]
Fixed.
