### ISSUE TITLE
N1ghtshade b12 stuck on 'Executing Payload' | macOS Sierra 10.12.6

### ISSUE THREAD

**Issue by hanlywijaya** [synackuk/n1ghtshade#23]
Hello, developer 'synackuk'. I recently tried to restore my iPad (4th generation with 128gb from Jan 2013) with n1ghtshade on the latest beta, 12, but whenever I try to restore it, it gets stuck on 'Executing Payload'. Tried several versions of n1ghtshade but nothing. My Mac specifications is below.
iMac (27-inch late 2012)
macOS Sierra
10.12.6
Hope, you can help.
Cheers mate!
EDIT: My iPad 4 is specifically, an A1460 (global) model.

**Comment by hanlywijaya** [comment]
Just tried n1ghtshade beta 9, it's also stuck on 'Executing payload' as well. I'll try to update you later.

**Comment by ToreHQ12** [comment]
It work?i have same issue

**Comment by synackuk** [comment]
@hanlywijaya @ToreHQ12 
[n1ghtshade-beta.zip](https://github.com/synackuk/n1ghtshade/files/4024645/n1ghtshade-beta.zip)
 Can you try this version

**Comment by WendigoTV** [comment]
Same problem with iPhone 5 & Catalina, beta.zip doesn't work either

**Comment by synackuk** [comment]
This is fixed in [n1ghtshade rc1](https://github.com/synackuk/n1ghtshade/releases/tag/RC1),  you must re-restore your device after upgrading to it.
