### ISSUE TITLE
iPhone 5 losing cellular service after jailbreaking

### ISSUE THREAD

**Issue by omarthen3rd** [synackuk/n1ghtshade#26]
A successful restore + tethered boot allows all phone functions to work normally, but as soon as it's jailbroken and then a tethered boot is performed, cellular service is lost. 'Searching...' shows up for a couple of minutes and then resorts to 'No Service'. Testing on iOS 6.1.4 + 7.1.2 on an iPhone 5,1.

**Comment by synackuk** [comment]
Related #28 But I think I can fix this

**Comment by marleyqp** [comment]
Is there any way to undo the jailbreak? and is there an eta for next release? planning to use my iOS 6 device for a week xD

**Comment by ProgrammingHider** [comment]
Can Confirm, iOS 6.1.4 iPhone 5 Global, Cellular stops working after Jailbreak.

**Comment by amit9179** [comment]
How to jailbreak iphone 5 after tethered boot. I’m using Pangu tool. It reboots the device nd device stucks on boot everytime.

**Comment by synackuk** [comment]
This is fixed in [n1ghtshade rc1](https://github.com/synackuk/n1ghtshade/releases/tag/RC1),  you must re-restore your device after upgrading to it.
