### ISSUE TITLE
Error while trying to build

### ISSUE THREAD

**Issue by pappanunny** [synackuk/n1ghtshade#27]
Hi, 
I'm trying to build n1ghtshade, and am facing an issue as shown below:

> Making stage for tool non_default_apps…
Building jb_init
> Making all for tool jb_init…
==> Compiling main.m (armv7)…
==> Linking tool jb_init (armv7)…
clang: warning: libstdc++ is deprecated; move to libc++ with a minimum deployment target of iOS 7 [-Wdeprecated]
Undefined symbols for architecture armv7:
  "_strcmp", referenced from:
      _main in main.m.e38a04da.o
ld: symbol(s) not found for architecture armv7
clang: error: linker command failed with exit code 1 (use -v to see invocation)
make[5]: *** [/Users/csg3206/Documents/Pk/myTools/n1ghtshade-B12/physostigmine/jb_init/.theos/obj/debug/armv7/jb_init] Error 1
make[4]: *** [/Users/csg3206/Documents/Pk/myTools/n1ghtshade-B12/physostigmine/jb_init/.theos/obj/debug/armv7/jb_init] Error 2
make[3]: *** [internal-tool-all_] Error 2
make[2]: *** [jb_init.all.tool.variables] Error 2
make[1]: *** [jb_init] Error 2
make: *** [physostigmine] Error 2

What am I missing here and how can I fix this? Am I missing any libraries? 

Please point me in the right direction.

**Comment by synackuk** [comment]
Seems like an issue with your install of theos

**Comment by pappanunny** [comment]
Not theos, the sdk in theos. I had fixed this, but forgot to follow up and close it. Thank you very much for the response.
