### ISSUE TITLE
GPS not working @ iPhone 5, iOS 6.1.3

### ISSUE THREAD

**Issue by modemm** [synackuk/n1ghtshade#28]
After booting GPS location is not working at iPhone 5, iOS 6.1.3, done by n1ghtshade beta 12 on OS X High Sierra

**Comment by synackuk** [comment]
I think this may be an issue with the baseband, something I'm unable to rectify

**Comment by synackuk** [comment]
This is fixed in [n1ghtshade rc1](https://github.com/synackuk/n1ghtshade/releases/tag/RC1),  you must re-restore your device after upgrading to it.
