### ISSUE TITLE
Problem Jailbreak 5

### ISSUE THREAD

**Issue by frankl1m** [synackuk/n1ghtshade#3]
Is stucked in "Grouming heap", i tried for several times the same, one time only i get Booting message in iPhone

**Comment by frankl1m** [comment]
or if not i receive this error

**Comment by synackuk** [comment]
@frankl1m Can you run from terminal with LIBUSB_DEBUG=3 before n1ghtshade? What macOS version and what device?

**Comment by synackuk** [comment]
@frankl1m try the latest beta.

**Comment by synackuk** [comment]
Closing as issue fixed
