### ISSUE TITLE
Unable to boot after installing Rocket bootstrap because of Launchctl error

### ISSUE THREAD

**Issue by KalThemes** [synackuk/n1ghtshade#30]
I restored iphone 5C on iOS 7 but after installing Rocket bootstrap i can't boot my device. on verbose boot it give me Launchctl error.
![IMG_20191229_072639__01](https://user-images.githubusercontent.com/55291853/71648351-2243d000-2d29-11ea-9913-7025cf8c58a8.jpg)

**Comment by SashaLobanov** [comment]
I think that iPhone 5C is not supported. Look at the comments. Nobody could downgrade iPhone 5C, so I think it’s unsupported

**Comment by KalThemes** [comment]
@SashaLobanov I'm able to restore with N1ghtshade successfully but after installing Rocket bootstrap i can't boot it give me Launchctl error on verbose boot

**Comment by synackuk** [comment]
This issue is being investigated, the jailbreak patching utility will be greatly improved in the next beta.

**Comment by KalThemes** [comment]
@synackuk Even Filza and many other tweaks not working giving weird errors

**Comment by synackuk** [comment]
This is fixed in [n1ghtshade rc1](https://github.com/synackuk/n1ghtshade/releases/tag/RC1),  you must re-restore your device after upgrading to it.
