### ISSUE TITLE
FaceTime app disappeared? (iPhone 5)

### ISSUE THREAD

**Issue by marleyqp** [synackuk/n1ghtshade#33]
Don’t know why but FaceTime app and functionality has gone! I can make FaceTime calls from messages for a split second then it says unavailable

**Comment by synackuk** [comment]
I believe this is due to the hactivation used within n1ghtshade. I'm working on a system for disabling this.

**Comment by marleyqp** [comment]
Also, iOS 7 doesn’t have this issue. Tested yesterday

**Comment by synackuk** [comment]
This is fixed in [n1ghtshade rc1](https://github.com/synackuk/n1ghtshade/releases/tag/RC1),  you must re-restore your device after upgrading to it.
