### ISSUE TITLE
Bluetooth & AirPlay not working on iOS 7 (N1ghtshade beta 12)

### ISSUE THREAD

**Issue by bodenchristian** [synackuk/n1ghtshade#34]
So I successfully downgraded my iPhone 5 to iOS 7.0 and 7.0.6 plus tried everything in between, but Bluetooth is not an option in settings and in Control Center clicking it doesn't do anything. Bluetooth did work though in iOS 10.3.4. When I try to connect to AirPlay (Which works on my iPhone 8 & 7), it shows that it's connected but when I go to play the video or song, it disconnects. TIA, and I can provide any logs if you need them.

**Comment by synackuk** [comment]
@bodenchristian I'm also having the bluetooth issue, will investigate

**Comment by synackuk** [comment]
This is fixed in [n1ghtshade rc1](https://github.com/synackuk/n1ghtshade/releases/tag/RC1),  you must re-restore your device after upgrading to it.
