### ISSUE TITLE
n1ghtshade b12 stucks on "Executing payload" and then crushes (iPhone 5C, Catalina 10.15.2) 

### ISSUE THREAD

**Issue by iponurovskiy** [synackuk/n1ghtshade#35]
When I try to Jailbreak or Boot Tethered iPhone 5C with the latest n1ghtshade Beta, the utility stucks on "Executing payload" step for a while and then crushes with Segmentation fault. My environment is Mac OS Catalina 10.15.2.

**Comment by synackuk** [comment]
Can you send the full error log @iponurovskiy

**Comment by jailhousej** [comment]
[Use the beta in this issue post](https://github.com/synackuk/n1ghtshade/issues/10)

**Comment by synackuk** [comment]
@iponurovskiy All checkm8 related issues should be fixed in the upcoming version.

**Comment by synackuk** [comment]
This is fixed in [n1ghtshade rc1](https://github.com/synackuk/n1ghtshade/releases/tag/RC1),  you must re-restore your device after upgrading to it.
