### ISSUE TITLE
No Cydia or jailbreaking apps on ios 7 +

### ISSUE THREAD

**Issue by Charliefr3sh** [synackuk/n1ghtshade#36]
cannot install cydia or any other alternatives on ipad 4 running ios 7

**Comment by synackuk** [comment]
What error do you recieve @Charliefr3sh

**Comment by Charliefr3sh** [comment]
There's no error, everything goes well, but there's no Cydia installed on the home screen. But the iPad does show that's jailbroken

**Comment by synackuk** [comment]
@Charliefr3sh did you run the jailbreak option?
