### ISSUE TITLE
Always failed to enter pwned dfu mode

### ISSUE THREAD

**Issue by megabitsenmzq** [synackuk/n1ghtshade#37]
iPhone 5,2
iOS 10.3.4
Catalina 10.15.3

**Comment by Chicko-iOS** [comment]
Probably because you are on Catalina. Not sure, but I think that Catalina is broken.

**Comment by megabitsenmzq** [comment]
> Probably because you are on Catalina. Not sure, but I think that Catalina is broken.

I tried to use nightshade on other Mac and VM, it always fail.
I also tried to use ipwndfu directly, and it worked.

**Comment by Chicko-iOS** [comment]
I've just had... bad experiences with Catalina.

**Comment by Chicko-iOS** [comment]
> > Probably because you are on Catalina. Not sure, but I think that Catalina is broken.
> 
> I tried to use nightshade on other Mac and VM, it always fail.
> I also tried to use ipwndfu directly, and it worked.

I wonder what's happening...

**Comment by synackuk** [comment]
This is fixed in [n1ghtshade rc1](https://github.com/synackuk/n1ghtshade/releases/tag/RC1),  you must re-restore your device after upgrading to it.
