### ISSUE TITLE
"Connect to iTunes to use Push Notification"

### ISSUE THREAD

**Issue by thisismartinn** [synackuk/n1ghtshade#39]
Notification on apps (e.g Spotify, YouTube) won't work at all, asked user to connect to iTunes. I connected to iTunes and it does nothing. iPhone 5,2 w/ iOS 6.1.4.

I think this issue is related to #28 as well.

**Comment by synackuk** [comment]
This issue is due to hactivation, I am thinking of adding an option to disable hacktivation in the upcoming version which will fix this

**Comment by synackuk** [comment]
This is fixed in [n1ghtshade rc1](https://github.com/synackuk/n1ghtshade/releases/tag/RC1),  you must re-restore your device after upgrading to it.
