### ISSUE TITLE
failed to enter pwned dfu recovery mode

### ISSUE THREAD

**Issue by ToreHQ12** [synackuk/n1ghtshade#41]
i got always this error, in all the beta's

**Comment by jailhousej** [comment]
use the beta linked to issue 10
[here](https://github.com/synackuk/n1ghtshade/issues/10)

**Comment by synackuk** [comment]
This is fixed in [n1ghtshade rc1](https://github.com/synackuk/n1ghtshade/releases/tag/RC1),  you must re-restore your device after upgrading to it.
