### ISSUE TITLE
Can I downgrade iPhone 5 to iOS 6?

### ISSUE THREAD

**Issue by NikkotheAIDEV** [synackuk/n1ghtshade#42]

**Comment by iptv69** [comment]
yes

**Comment by nguyenthanh1001** [comment]
How to downgrade iPhone 5 from iOS 10.3.4 to iOS 6.0 . https://youtu.be/eOCSlMMERSE

**Comment by synackuk** [comment]
yes

**Comment by MatrixBGD** [comment]
Anything I do I cannot overcome the Error Unable to connect to FDR client (-2)
iPhone 5 ; MacOS 10.4.6 n1ghtshade V 0.01 (have tried also Beda Version, didn't work).
I am pretty sure that I have entered into DFU mode correctly.
