### ISSUE TITLE
Failed to enter pwned recovery mode

### ISSUE THREAD

**Issue by mrichardist** [synackuk/n1ghtshade#43]
iPhone 5,2 
Mac OS X Sierra
iOS 6.0.2, 6.1, 7.0.6

I've tried all the betas every since Sierra support but no luck. I can't enter pwndfu mode via n1ghtshade so I manually enter pwndfu mode via terminal. I keep getting Failed to enter pwned recovery mode

**Comment by synackuk** [comment]
This is fixed in [n1ghtshade rc1](https://github.com/synackuk/n1ghtshade/releases/tag/RC1),  you must re-restore your device after upgrading to it.
