### ISSUE TITLE
After "Restoring Device" It says "Failed to restore device"

### ISSUE THREAD

**Issue by ithamarkap** [synackuk/n1ghtshade#45]
iPhone 5c 5,3, MacOS Mojave Mac Mini 2011.

**Comment by synackuk** [comment]
The upcoming version will include a new idevicerestore, hopefully rectifying these issues.

**Comment by ithamarkap** [comment]
Thank you very much!

**Comment by synackuk** [comment]
This is fixed in [n1ghtshade rc1](https://github.com/synackuk/n1ghtshade/releases/tag/RC1),  you must re-restore your device after upgrading to it.
