### ISSUE TITLE
Iphone don't boot anymore

### ISSUE THREAD

**Issue by arckadious** [synackuk/n1ghtshade#47]
MacOS Sierra, Iphone 5c. I used the beta 12. Sometimes, I have to restart again my Iphone to put it again in DFU Mode, to make nightshade detect the iphone in DFU. I tried two ipsw : 7.1.2 for iphone 5c and 7.0.2 for iphone 5c.

The problem is in the end of the installation (nightshade show "Done"), because the phone don't reboot anymore (no apple logo). One another thing, the DFU mode is still working but only with iTunes, not with the nightshade application (stuck in "execute payload" at each try). So to retry a downgrade (' and so not be stuck in execute payload'), I had to put the iOS 10.3.3 first, and then try again with nightshade.

**Comment by arckadious** [comment]
I tried to boot thetered even if the iPhone didn't boot after the downgrade, but it's still not working (stuck on "execute payload" again).

**Comment by arckadious** [comment]
finally i found, i had to try again and again

**Comment by arckadious** [comment]
So basically, the iPhone work, but there is one problem, when I turn off my phone, and turn on again, it don't boot anymore, so I have to do a boot thetered again to make it boot properly..

**Comment by MattStar45** [comment]
This is not an issue with n1ghtshade, that’s just the nature of using tools like it, please close the issue
