### ISSUE TITLE
Cannot Use Bluetooth In 7.0.6/7.1.2

### ISSUE THREAD

**Issue by Harold62** [synackuk/n1ghtshade#48]
No bluetooth pane in the settings app on either i7 version, on 7.1.2 it's greyed out in control centre, works fine on iOS6x

**Comment by synackuk** [comment]
This is fixed in [n1ghtshade rc1](https://github.com/synackuk/n1ghtshade/releases/tag/RC1),  you must re-restore your device after upgrading to it.
