### ISSUE TITLE
iPhone 5c iOS 9.2 stuck 

### ISSUE THREAD

**Issue by akshay7802** [synackuk/n1ghtshade#50]

**Comment by akshay7802** [comment]
Updating baseband (19)
Updating Baseband in progress...
About to send BasebandData...
Sending Baseband TSS request...
Request URL set to https://gs.apple.com/TSS/controller?action=2
Sending TSS request attempt 1... response successfully received
Received Baseband SHSH blobs

**Comment by synackuk** [comment]
@akshay7802 How long was n1ghtshade stuck here?

**Comment by akshay7802** [comment]
after 30 mins or so then it progressed and got stucked again on About to send basebandData

**Comment by synackuk** [comment]
30 mins? Seems like an internet problem or a problem with your usb cable

**Comment by akshay7802** [comment]
ok i'll just try again.
should i flash 10.3.3 first?

**Comment by synackuk** [comment]
@akshay7802 no need

**Comment by akshay7802** [comment]
Restoring device
ERROR: Unable to discover device mode. Please make sure a device is attached.
Error in libbelladonna.c:968 "Failed to restore device."Failed to restore IPSW.
