### ISSUE TITLE
Apps crash after jailbreak on iOS 7x

### ISSUE THREAD

**Issue by Harold62** [synackuk/n1ghtshade#53]
Also no apps will download after jailbreak, I'm guessing this is because there's no hacktivation? Also after a little while, cellular services/Imsg/Facetime all stop working, for me approx an hour after jailbreaking. Thanks for your hard work I really appreciate it.

**Comment by Harold62** [comment]
Just a side-note, All downloaded apps crash, including calendar, mail, weather, maps, calculator and safari. Tested on 7.0.6/7.2.1

**Comment by synackuk** [comment]
Merging with #55
