### ISSUE TITLE
Unable to restore iPhone 5 to iOS 7 and 8

### ISSUE THREAD

**Issue by CodeyMoore** [synackuk/n1ghtshade#54]
iPhone 5 on iOS 10.3.4 unable to restore to iOS 7 and 8 using N1ghtShade

Log below
"checkm8 by axi0mX
Grooming heap
Preparing for overwrite
Grooming heap
Overwriting task struct
Uploading payload
Executing payload
Device is now in pwned DFU mode
Finding iBSS for device
Uploading iBSS
Executing iBSS
Finding iBEC for device
Uploading iBEC
Executing iBEC
Uploading atropine hooker
Executing hooker
Uploading atropine
Loading payload
Restoring device
ERROR: Unable to discover device mode. Please make sure a device is attached.
Error in libbelladonna.c:968 "Failed to restore device."Failed to restore IPSW."

**Comment by CodeyMoore** [comment]
Fixed it by install all the dependencies.

**Comment by mariobrostech** [comment]
@CodeyMoore Do you mind explaining how you installed the following dependencies? I can't find them on Homebrew. Thanks in advance!
- arm-elf-gcc
- libcrypto
- libfragmentzip
