### ISSUE TITLE
Safari Doesn't work

### ISSUE THREAD

**Issue by HexagonWin** [synackuk/n1ghtshade#56]
Hi. I am using the iPhone5,2 16gb version.
I use my pc hackintosh 10.14.4 mojave.
I downgraded my phone to iOS 6.1.4, and after jailbreak and some time (didnt even install a tweak. just tapped install cydia in the app) the safari app stopped working. It crashes when i launch.
So, I downgraded to 7.1.2 and did the same. the same thing happens.
How can i fix this? is this theproblem of my phone?

**Comment by HexagonWin** [comment]
Add : I reinstalled the 6.1.4 and it seemed to work after jb.
After installing the tweak "Poof" it stopped working like first.
However, on a iPhone 4s that isn't upgraded since 6.1.4 and a another i5 with iOS 6.1.4 coolbooter, the tweak works fine.
Is it a problem with the tweak or the n`ghtshade?

**Comment by HexagonWin** [comment]
Add2 : It seems like the problem in the phone.
Also springtomize causes the issue too.
I tried on the other 5, and it has no problem.
Sorry,,

**Comment by HexagonWin** [comment]
After re-booting the other 5, the issue re-occurs.
I also tried to remove the tweak, and still the same.
I did the exact same thing on my 4s and it had no problem
I think it is. a problem with this..

**Comment by HexagonWin** [comment]
Also add : Now, I also found out that the mail app also stopps working.
I tested 7.1.2, 6.1.4, and 6.1.0 now. everything has the same problem.
Even in 6.1.0, i just jailbroke and finished upgrade for things on cydia and installed nothing. After reboot, safari and mail crashes!

**Comment by synackuk** [comment]
Hello, I shall investigate this...

**Comment by HexagonWin** [comment]
Thanks!
Also, when i install tweak named BatteryDoctorPro the same thing happens but it is only sometimes.
The Beta versions are all failing on my hackintosh so i cannot test other versions

**Comment by HexagonWin** [comment]
Tested RC3 now, and the issue is the same.
I wish this gets solved.
Also, I found out that it works in Safe Mode.
But no suspect in CrashReporter

**Comment by HexagonWin** [comment]
Should I post the log in CrashReporter?
I am using it as a main phone and I am tired of Safari

**Comment by HexagonWin** [comment]
So, i found a way to fix this!
The reason is because n1ghtshade's jb installs a bit older version of Cydia Substrate
So, I deleted Cydia Substrate and then installed the 0.9.7100 version of it from the repo.mtmdev.org repo.
This fixes all the problem and it all works!
@synackuk I think you have to change the version of Cydia Substrate that n1ghtshade installs

**Comment by B3ATDROP3R** [comment]
I am commenting here because I believe the owner should at least include something about this in the readme for others (like myself) who had this issue.
