### ISSUE TITLE
Support for virtual machine/older macOS

### ISSUE THREAD

**Issue by SaadAbbassi4** [synackuk/n1ghtshade#58]
Hey!
I have an old MacBook (early 2011) but it only supports up to High Sierra (10.13.6) could I run it on a virtual machine?
TIA
Edit: or even better, can I run it on 10.13?

**Comment by synackuk** [comment]
@SaadAbbassi4 I wasn't aware n1ghtshade doesn't run on high sierra? I'll look into this

**Comment by HexagonWin** [comment]
I think even the Beta versions work in Sierra (not high sierra)
I had used this tool when i had my sierra hackintosh pc.

**Comment by SaadAbbassi4** [comment]
Yeah, but only beta versions not the RC ones

Le mer. 8 juil. 2020 à 11:40, HexagonWin <notifications@github.com> a
écrit :
