### ISSUE TITLE
iPhone 5c Unable to send RestoreLogo to device when running idevicerestore

### ISSUE THREAD

**Issue by slingalist** [synackuk/n1ghtshade#6]
ERROR: Unable to send RestoreLogo component: Unable to find device ERROR: Unable to send RestoreLogo to device. ERROR: Unable to send AppleLogo ERROR: Unable to place device into restore mode Error in libbelladonna_restore_ipsw (libbelladonna.c:594) "Failed to restore device." 2019-12-09 20:02:43.852 n1ghtshade[50853:198706] Failed to restore device

iPhone 5c (Global)
macOS 10.13 (High Sierra)

Same error with ipsw: 7.0.1, 7.0.5 and 8.4

**Comment by wutiswrongxd** [comment]
Having the exact same issue here.

**Comment by jaxx635** [comment]
same

**Comment by synackuk** [comment]
@slingalist Thank you, I have heard a few reports of this. Trying to find common variables currently.

**Comment by slingalist** [comment]
> @slingalist Thank you, I have heard a few reports of this. Trying to find common variables currently.

I got it to work with beta 5

Tested with;
iOS 7.0.1
iOS 7.05

**Comment by synackuk** [comment]
This may be fixed in beta 12

**Comment by synackuk** [comment]
This is fixed in [n1ghtshade rc1](https://github.com/synackuk/n1ghtshade/releases/tag/RC1),  you must re-restore your device after upgrading to it.
