### ISSUE TITLE
RC2 and RC3 both incompatible with 10.14.6 Mojave?

### ISSUE THREAD

**Issue by Harold62** [synackuk/n1ghtshade#62]
RC2 error: Check with the developer to make sure n1ghtshade works with this version of macOS. You may need to reinstall the application. Be sure to install any available updates for the application and macOS.

RC3 error: You can't open the application "n1ghtshade" because it may be damaged or incomplete.

**Comment by synackuk** [comment]
@Harold62 Please redownload RC3?

**Comment by Harold62** [comment]
That’s the first thing I tried

**Comment by Harold62** [comment]
Works on my other Mac.
