### ISSUE TITLE
Not work 

### ISSUE THREAD

**Issue by sdrtgfdsqzer** [synackuk/n1ghtshade#63]
Not work with 

iOS 6 iPad 2 Rev 2012 (iPad2,4) 
iOS 8 iPad 2 Rev 2012 (iPad2,4) 
iOS 6 iPad 3 (iPad 3,2) 
iOS 8 iPad Mini 1
iOS 6 iPad Mini 1

**Comment by SaadAbbassi4** [comment]
BECAUSE IT'S ONLY COMPATIBLE WITH A6 AND A6X (iPhone 5/iPad 4)
