### ISSUE TITLE
"Error in libbelladonna.c:845 "Failed to download kernel.""

### ISSUE THREAD

**Issue by SaadAbbassi4** [synackuk/n1ghtshade#65]
Hey! 
I tried to activate 8.4.1 with n1ghtshade but it won't work it gives me this error:
`Error in libbelladonna.c:845 "Failed to download kernel."`
Thanks!

**Comment by Iphone5-RecoveryMode** [comment]
I also had a problem with libbelladonna. Ill be trying to uninstall n1ghtshade and will try to use the release before.

**Comment by synackuk** [comment]
@SaadAbbassi4 What iPhone?

**Comment by SaadAbbassi4** [comment]
iPad 4

**Comment by obsolete00** [comment]
I got the same message on iPad 4 A1458

**Comment by SaadAbbassi4** [comment]
> I got the same message on iPad 4 A1458

Did you found a solution?
