### ISSUE TITLE
Unable to boot since RC releases

### ISSUE THREAD

**Issue by CenoX** [synackuk/n1ghtshade#66]
I restored my iPhone 5 to iOS 6.1.4 on n1ghtshade beta 10.

Until Beta 12, it often didn't work, but sometimes it success and booted.
(stuck in `grooming heap` or `Downloading iBSS | iBEC` state or crash)
However, after the RC release, the boot loader screen appears, but it stops and does not proceed.

If I have to wait in that state, please close the issue.
If not, please notice me how to resolve it or investigate this issue.

+Added
Tried to boot on All RC Versions.
iOS Version: 6.1.4, jailbroken by p0sixspwn
macOS Version: macOS Catalina (10.15.5)

**Comment by thisismartinn** [comment]
You have to restore your iOS version when "upgrading" to RC1 and later, you can't boot your restored-with-Beta12 iOS with RC1.

**Comment by CenoX** [comment]
Thanks for quick reply. but there is no description about that.
How about add that description on README or somewhere?

**Comment by thisismartinn** [comment]
He did posted that on Twitter tho: https://twitter.com/synackuk/status/1275224141692653568

**Comment by CenoX** [comment]
Oh twitter... checked
