### ISSUE TITLE
No n1ghtshade app on the iPhone 5C homescreen on jailbroken iOS 9.0 beta 1 

### ISSUE THREAD

**Issue by p0sin** [synackuk/n1ghtshade#69]
I just tethered downgraded to iOS 9.0 beta 1 on my iPhone 5C and tethered jailbroke with n1ghtshade as well. There's absolutely no n1ghtshade app on the device's homescreen at all. Been working on fixing this literally all day. No solution yet. Even turned off Bluetooth on both my Mac and iOS device in hopes of resolving this issue. My Mac I use n1ghtshade on is a MacBook Pro early 2015 with macOS Mojave 10.14.6 installed, and my iPhone 5C is a 32GB model, if that helps... Any ideas?

**Comment by Iphone5-RecoveryMode** [comment]
there isn't a nightshade app.

**Comment by p0sin** [comment]
> there isn't a nightshade app.

Might be because n1ghtshade doesn't support jailbreaking iOS 8.0 - 9.3.5 or iOS 10 yet.

**Comment by synackuk** [comment]
@p0sin Interesting, I've not tried beta versions so this may be an issue. Will investigate

**Comment by p0sin** [comment]
@synackuk Thanks for investigating.

**Comment by Seu07** [comment]
@synackuk Excuse me, I used n1ghtshade  to downgrade iPad4 to ios 9.2.1 successfully. But no luck to jailbreak it. Do we still have way to jailbreak after tethered downgrade? Thanks)
