### ISSUE TITLE
iPhone 5C device not detected by idevicerestore after executing iBoot payload

### ISSUE THREAD

**Issue by KalThemes** [synackuk/n1ghtshade#7]
It's just giving restore failed error and on iphone screen it's stuck on 
pwned by synAck
Initialised atropine.

**Comment by synackuk** [comment]
What macOS version? What iOS version are you attempting to restore?

**Comment by KalThemes** [comment]
MacOS Mojave 
And I tried iOS 7.1.2, 7.0.4, 7.0.1 & 7.1 versions.
But encounter same error.
I also install libusb, homebrew and many other dependencies but still no luck.

**Comment by KalThemes** [comment]
@synackuk 
MacOS Mojave
And I tried iOS 7.1.2, 7.0.4, 7.0.1 & 7.1 versions.
But encounter same error.
I also install libusb, homebrew and many other dependencies but still no luck.

**Comment by KalThemes** [comment]
@synackuk still not fix?

**Comment by synackuk** [comment]
Please try with the latest beta

**Comment by synackuk** [comment]
This is fixed in [n1ghtshade rc1](https://github.com/synackuk/n1ghtshade/releases/tag/RC1),  you must re-restore your device after upgrading to it.
