### ISSUE TITLE
Mail and Safari do not launch on iPhone 5,1 64GB iOS 6.0

### ISSUE THREAD

**Issue by DonkeyKongJr1982** [synackuk/n1ghtshade#72]
These two apps crash on launch.

**Comment by thisismartinn** [comment]
This is a compatibility issue with the current version of Cydia Substrate. 

You should update the substrate to version 0.9.7101 via the repo http://repo.mtmdev.org/ to fix the issue.

**Comment by DonkeyKongJr1982** [comment]
i'm stupid lmao
