### ISSUE TITLE
Ipad 4 stuck on Restore Device ?

### ISSUE THREAD

**Issue by oyeanu** [synackuk/n1ghtshade#8]

**Comment by synackuk** [comment]
@oyeanu What iOS version are you trying to restore? What macOS version are you running?

**Comment by oyeanu** [comment]
> @oyeanu What iOS version are you trying to restore? What macOS version are you running?

IOS 6.1.3 macOS 10.14

**Comment by synackuk** [comment]
@oyeanu Please try with beta 12

**Comment by synackuk** [comment]
Closing as fixed
