### ISSUE TITLE
iPhone 5C doesn't boot anymore.

### ISSUE THREAD

**Issue by hrishi1992** [synackuk/n1ghtshade#86]
I'm using MacOS High Sierra. I tried using the RC3 and Beta 12 of n1ghtshade to downgrade iPhone 5C(A1529) from iOS 10.3.3 to iOS 7.1.2/iOS 8.4.1. n1ghtshade says done everytime but the iPhone doesn't boot up. No logo. Nothing. Only itunes detects it and then I had to restore it back up to 10.3.3 and tried again except this time on iOS 8.4.1. Nothing changed. It still doesn't boot up. Am I doing something wrong here? Please help.

**Comment by zaxkh** [comment]
Did you use the boot tethered option after the restore?

**Comment by hrishi1992** [comment]
> Did you use the boot tethered option after the restore?

Thank you so much. That did the trick. I feel so dumb. Well at least someone else having the same problem doesn't need to make a new thread. Downgraded successfully back to 7.1.2.

I have 2 questions-
Can I restart the phone without having to worry about anything?
Also any way to turn off two step verification? I can't seem to login to iPhone 5c. It doesn't show the page prompting to enter 6 digit code.

**Comment by freza1** [comment]
@hrishi1992 I downgraded from iOS 10.3.3 to iOS 8.1.2 and I can't seem to restart it. I retried the Boot Tethering option, and it kept saying "Failed to pwn device in dfu mode" with a 689 error. There seemed to be a boot loop occurring and the phone wouldn't stay in DFU. Were you able to find a fix? Also to answer your second question, two step can be turned off in your apple account, or iTunes.

**Comment by hrishi1992** [comment]
> @hrishi1992 I downgraded from iOS 10.3.3 to iOS 8.1.2 and I can't seem to restart it. I retried the Boot Tethering option, and it kept saying "Failed to pwn device in dfu mode" with a 689 error. There seemed to be a boot loop occurring and the phone wouldn't stay in DFU. Were you able to find a fix? Also to answer your second question, two step can be turned off in your apple account, or iTunes.

For me boot tethered worked. I tried Beta11 and RC3. I preferred Beta11. Easier to use. I'm guessing you have find a way to keep your phone from rebooting 'EVER'. If it reboots then you only have one option to connect to itunes and flash it with iOS 10.3.3(for 5C) and then rinse and repeat the entire process until you succeed. Kudos to the developers efforts but I have found little use because my battery drains like 50% in standby. Loved the fluidity of iOS 8 and iOS 7(Yes I could go to both OS-es) but alas gotta be stuck with iOS 10.3.3.

**Comment by hrishi1992** [comment]
I didn't come across that particular issue. I'm sorry I can't be of more help.

**Comment by hrishi1992** [comment]
I didn't come across that particular issue. I'm sorry I can't be of more help

**Comment by darbysauter** [comment]
So after restoring the only way to boot is tethered? Also is there a way of jailbreaking as well? seems to me the only way to boot is the tethered boot option, the jailbreak option didnt seem to work.
